runtime: nodejs20
env: standard

handlers:
  # Serve all static files with urls ending with a file extension
  - url: /(.*\.(?:css|html|js|ico|jpg|jpeg|png|svg|woff|woff2|ttf|map))$
    static_files: build/\1
    upload: build/(.*\.(?:css|html|js|ico|jpg|jpeg|png|svg|woff|woff2|ttf|map))$
  # Serve index.html for all other requests to enable SPA routing
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

env_variables:
  NODE_ENV: 'production'