const mock_data = {
  "current": {
    "cloud": 0,
    "condition": {
      "code": 1000,
      "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
      "text": "Clear"
    },
    "feelslike_c": 16.0,
    "feelslike_f": 60.8,
    "gust_kph": 14.5,
    "gust_mph": 9.0,
    "humidity": 88,
    "is_day": 0,
    "last_updated": "2024-04-10 23:15",
    "last_updated_epoch": 1712762100,
    "precip_in": 0.02,
    "precip_mm": 0.56,
    "pressure_in": 30.06,
    "pressure_mb": 1018.0,
    "temp_c": 16.0,
    "temp_f": 60.8,
    "uv": 1.0,
    "vis_km": 10.0,
    "vis_miles": 6.0,
    "wind_degree": 80,
    "wind_dir": "E",
    "wind_kph": 11.2,
    "wind_mph": 6.9
  },
  "forecast": {
    "forecastday": [
      {
        "astro": {
          "is_moon_up": 1,
          "is_sun_up": 1,
          "moon_illumination": 2,
          "moon_phase": "Waxing Crescent",
          "moonrise": "06:26 AM",
          "moonset": "08:25 PM",
          "sunrise": "05:42 AM",
          "sunset": "06:31 PM"
        },
        "date": "2024-04-10",
        "date_epoch": 1712707200,
        "day": {
          "avghumidity": 68,
          "avgtemp_c": 15.4,
          "avgtemp_f": 59.8,
          "avgvis_km": 8.7,
          "avgvis_miles": 5.0,
          "condition": {
            "code": 1063,
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "text": "Patchy rain nearby"
          },
          "daily_chance_of_rain": 88,
          "daily_chance_of_snow": 0,
          "daily_will_it_rain": 1,
          "daily_will_it_snow": 0,
          "maxtemp_c": 20.5,
          "maxtemp_f": 68.9,
          "maxwind_kph": 23.8,
          "maxwind_mph": 14.8,
          "mintemp_c": 12.0,
          "mintemp_f": 53.6,
          "totalprecip_in": 0.06,
          "totalprecip_mm": 1.55,
          "totalsnow_cm": 0.0,
          "uv": 5.0
        },
        "hour": [
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 6,
            "condition": {
              "code": 1000,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "text": "Clear "
            },
            "dewpoint_c": 10.1,
            "dewpoint_f": 50.2,
            "feelslike_c": 13.9,
            "feelslike_f": 57.0,
            "gust_kph": 23.4,
            "gust_mph": 14.6,
            "heatindex_c": 14.7,
            "heatindex_f": 58.4,
            "humidity": 74,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.18,
            "pressure_mb": 1022.0,
            "snow_cm": 0.0,
            "temp_c": 14.7,
            "temp_f": 58.4,
            "time": "2024-04-10 00:00",
            "time_epoch": 1712678400,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 103,
            "wind_dir": "ESE",
            "wind_kph": 12.6,
            "wind_mph": 7.8,
            "windchill_c": 13.9,
            "windchill_f": 57.0
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 46,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.4,
            "feelslike_c": 13.2,
            "feelslike_f": 55.7,
            "gust_kph": 22.9,
            "gust_mph": 14.2,
            "heatindex_c": 14.0,
            "heatindex_f": 57.2,
            "humidity": 75,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.16,
            "pressure_mb": 1022.0,
            "snow_cm": 0.0,
            "temp_c": 14.0,
            "temp_f": 57.2,
            "time": "2024-04-10 01:00",
            "time_epoch": 1712682000,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 102,
            "wind_dir": "ESE",
            "wind_kph": 11.9,
            "wind_mph": 7.4,
            "windchill_c": 13.2,
            "windchill_f": 55.7
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 54,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 9.7,
            "dewpoint_f": 49.4,
            "feelslike_c": 12.5,
            "feelslike_f": 54.5,
            "gust_kph": 24.8,
            "gust_mph": 15.4,
            "heatindex_c": 13.5,
            "heatindex_f": 56.3,
            "humidity": 77,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.15,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 13.5,
            "temp_f": 56.3,
            "time": "2024-04-10 02:00",
            "time_epoch": 1712685600,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 103,
            "wind_dir": "ESE",
            "wind_kph": 12.6,
            "wind_mph": 7.8,
            "windchill_c": 12.5,
            "windchill_f": 54.5
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 50,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 9.5,
            "dewpoint_f": 49.1,
            "feelslike_c": 12.2,
            "feelslike_f": 53.9,
            "gust_kph": 25.6,
            "gust_mph": 15.9,
            "heatindex_c": 13.3,
            "heatindex_f": 55.9,
            "humidity": 78,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.13,
            "pressure_mb": 1020.0,
            "snow_cm": 0.0,
            "temp_c": 13.3,
            "temp_f": 55.9,
            "time": "2024-04-10 03:00",
            "time_epoch": 1712689200,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 110,
            "wind_dir": "ESE",
            "wind_kph": 13.3,
            "wind_mph": 8.3,
            "windchill_c": 12.2,
            "windchill_f": 53.9
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 49,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 8.6,
            "dewpoint_f": 47.5,
            "feelslike_c": 12.1,
            "feelslike_f": 53.8,
            "gust_kph": 25.9,
            "gust_mph": 16.1,
            "heatindex_c": 13.3,
            "heatindex_f": 56.0,
            "humidity": 73,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.13,
            "pressure_mb": 1020.0,
            "snow_cm": 0.0,
            "temp_c": 13.3,
            "temp_f": 56.0,
            "time": "2024-04-10 04:00",
            "time_epoch": 1712692800,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 117,
            "wind_dir": "ESE",
            "wind_kph": 14.0,
            "wind_mph": 8.7,
            "windchill_c": 12.1,
            "windchill_f": 53.8
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 47,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 7.2,
            "dewpoint_f": 44.9,
            "feelslike_c": 11.5,
            "feelslike_f": 52.7,
            "gust_kph": 24.6,
            "gust_mph": 15.3,
            "heatindex_c": 12.7,
            "heatindex_f": 54.9,
            "humidity": 69,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.14,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 12.7,
            "temp_f": 54.9,
            "time": "2024-04-10 05:00",
            "time_epoch": 1712696400,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "wind_kph": 12.6,
            "wind_mph": 7.8,
            "windchill_c": 11.5,
            "windchill_f": 52.7
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 46,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 6.1,
            "dewpoint_f": 43.0,
            "feelslike_c": 10.6,
            "feelslike_f": 51.0,
            "gust_kph": 27.9,
            "gust_mph": 17.3,
            "heatindex_c": 12.0,
            "heatindex_f": 53.6,
            "humidity": 67,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.14,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 12.0,
            "temp_f": 53.6,
            "time": "2024-04-10 06:00",
            "time_epoch": 1712700000,
            "uv": 4.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 108,
            "wind_dir": "ESE",
            "wind_kph": 13.3,
            "wind_mph": 8.3,
            "windchill_c": 10.6,
            "windchill_f": 51.0
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 41,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 6.5,
            "dewpoint_f": 43.7,
            "feelslike_c": 11.6,
            "feelslike_f": 52.9,
            "gust_kph": 27.6,
            "gust_mph": 17.1,
            "heatindex_c": 13.0,
            "heatindex_f": 55.4,
            "humidity": 65,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.14,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 13.0,
            "temp_f": 55.4,
            "time": "2024-04-10 07:00",
            "time_epoch": 1712703600,
            "uv": 4.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 108,
            "wind_dir": "ESE",
            "wind_kph": 15.1,
            "wind_mph": 9.4,
            "windchill_c": 11.6,
            "windchill_f": 52.9
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 57,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 6.9,
            "dewpoint_f": 44.5,
            "feelslike_c": 13.0,
            "feelslike_f": 55.4,
            "gust_kph": 24.3,
            "gust_mph": 15.1,
            "heatindex_c": 14.2,
            "heatindex_f": 57.5,
            "humidity": 62,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.15,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 14.2,
            "temp_f": 57.5,
            "time": "2024-04-10 08:00",
            "time_epoch": 1712707200,
            "uv": 4.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "wind_kph": 15.5,
            "wind_mph": 9.6,
            "windchill_c": 13.0,
            "windchill_f": 55.4
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 80,
            "condition": {
              "code": 1006,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "text": "Cloudy "
            },
            "dewpoint_c": 8.0,
            "dewpoint_f": 46.3,
            "feelslike_c": 13.6,
            "feelslike_f": 56.5,
            "gust_kph": 23.4,
            "gust_mph": 14.6,
            "heatindex_c": 14.7,
            "heatindex_f": 58.4,
            "humidity": 64,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.16,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 14.7,
            "temp_f": 58.4,
            "time": "2024-04-10 09:00",
            "time_epoch": 1712710800,
            "uv": 3.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 111,
            "wind_dir": "ESE",
            "wind_kph": 15.5,
            "wind_mph": 9.6,
            "windchill_c": 13.6,
            "windchill_f": 56.5
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 85,
            "condition": {
              "code": 1006,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "text": "Cloudy "
            },
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.6,
            "feelslike_c": 15.0,
            "feelslike_f": 59.1,
            "gust_kph": 26.5,
            "gust_mph": 16.5,
            "heatindex_c": 15.0,
            "heatindex_f": 59.1,
            "humidity": 66,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.15,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 15.0,
            "temp_f": 59.1,
            "time": "2024-04-10 10:00",
            "time_epoch": 1712714400,
            "uv": 4.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 110,
            "wind_dir": "ESE",
            "wind_kph": 18.0,
            "wind_mph": 11.2,
            "windchill_c": 15.0,
            "windchill_f": 59.1
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 47,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 9.6,
            "dewpoint_f": 49.2,
            "feelslike_c": 16.3,
            "feelslike_f": 61.3,
            "gust_kph": 25.5,
            "gust_mph": 15.8,
            "heatindex_c": 16.3,
            "heatindex_f": 61.3,
            "humidity": 64,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.15,
            "pressure_mb": 1021.0,
            "snow_cm": 0.0,
            "temp_c": 16.3,
            "temp_f": 61.3,
            "time": "2024-04-10 11:00",
            "time_epoch": 1712718000,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 116,
            "wind_dir": "ESE",
            "wind_kph": 18.0,
            "wind_mph": 11.2,
            "windchill_c": 16.3,
            "windchill_f": 61.3
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 44,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 9.7,
            "dewpoint_f": 49.4,
            "feelslike_c": 17.4,
            "feelslike_f": 63.3,
            "gust_kph": 26.7,
            "gust_mph": 16.6,
            "heatindex_c": 17.4,
            "heatindex_f": 63.3,
            "humidity": 61,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.13,
            "pressure_mb": 1020.0,
            "snow_cm": 0.0,
            "temp_c": 17.4,
            "temp_f": 63.3,
            "time": "2024-04-10 12:00",
            "time_epoch": 1712721600,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 120,
            "wind_dir": "ESE",
            "wind_kph": 20.2,
            "wind_mph": 12.5,
            "windchill_c": 17.4,
            "windchill_f": 63.3
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 46,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 9.4,
            "dewpoint_f": 48.8,
            "feelslike_c": 20.4,
            "feelslike_f": 68.8,
            "gust_kph": 27.3,
            "gust_mph": 17.0,
            "heatindex_c": 20.4,
            "heatindex_f": 68.8,
            "humidity": 49,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.1,
            "pressure_mb": 1019.0,
            "snow_cm": 0.0,
            "temp_c": 20.4,
            "temp_f": 68.8,
            "time": "2024-04-10 13:00",
            "time_epoch": 1712725200,
            "uv": 6.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 125,
            "wind_dir": "SE",
            "wind_kph": 23.8,
            "wind_mph": 14.8,
            "windchill_c": 20.4,
            "windchill_f": 68.8
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 44,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 9.8,
            "dewpoint_f": 49.7,
            "feelslike_c": 20.5,
            "feelslike_f": 68.9,
            "gust_kph": 28.1,
            "gust_mph": 17.5,
            "heatindex_c": 20.5,
            "heatindex_f": 68.9,
            "humidity": 50,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.07,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 20.5,
            "temp_f": 68.9,
            "time": "2024-04-10 14:00",
            "time_epoch": 1712728800,
            "uv": 6.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 125,
            "wind_dir": "SE",
            "wind_kph": 23.4,
            "wind_mph": 14.5,
            "windchill_c": 20.5,
            "windchill_f": 68.9
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 63,
            "condition": {
              "code": 1006,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "text": "Cloudy "
            },
            "dewpoint_c": 10.6,
            "dewpoint_f": 51.0,
            "feelslike_c": 19.1,
            "feelslike_f": 66.3,
            "gust_kph": 27.6,
            "gust_mph": 17.1,
            "heatindex_c": 19.1,
            "heatindex_f": 66.3,
            "humidity": 58,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.06,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 19.1,
            "temp_f": 66.3,
            "time": "2024-04-10 15:00",
            "time_epoch": 1712732400,
            "uv": 4.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 126,
            "wind_dir": "SE",
            "wind_kph": 20.9,
            "wind_mph": 13.0,
            "windchill_c": 19.1,
            "windchill_f": 66.3
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 33,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 10.8,
            "dewpoint_f": 51.4,
            "feelslike_c": 18.3,
            "feelslike_f": 64.9,
            "gust_kph": 28.0,
            "gust_mph": 17.4,
            "heatindex_c": 18.3,
            "heatindex_f": 64.9,
            "humidity": 62,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.03,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 18.3,
            "temp_f": 64.9,
            "time": "2024-04-10 16:00",
            "time_epoch": 1712736000,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 123,
            "wind_dir": "ESE",
            "wind_kph": 20.5,
            "wind_mph": 12.8,
            "windchill_c": 18.3,
            "windchill_f": 64.9
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 54,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 10.9,
            "dewpoint_f": 51.5,
            "feelslike_c": 18.1,
            "feelslike_f": 64.6,
            "gust_kph": 26.0,
            "gust_mph": 16.2,
            "heatindex_c": 18.1,
            "heatindex_f": 64.6,
            "humidity": 62,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.04,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 18.1,
            "temp_f": 64.6,
            "time": "2024-04-10 17:00",
            "time_epoch": 1712739600,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 121,
            "wind_dir": "ESE",
            "wind_kph": 18.4,
            "wind_mph": 11.4,
            "windchill_c": 18.1,
            "windchill_f": 64.6
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1009,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "text": "Overcast "
            },
            "dewpoint_c": 10.6,
            "dewpoint_f": 51.1,
            "feelslike_c": 16.5,
            "feelslike_f": 61.7,
            "gust_kph": 25.6,
            "gust_mph": 15.9,
            "heatindex_c": 16.5,
            "heatindex_f": 61.7,
            "humidity": 68,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.04,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 16.5,
            "temp_f": 61.7,
            "time": "2024-04-10 18:00",
            "time_epoch": 1712743200,
            "uv": 4.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 118,
            "wind_dir": "ESE",
            "wind_kph": 15.8,
            "wind_mph": 9.8,
            "windchill_c": 16.5,
            "windchill_f": 61.7
          },
          {
            "chance_of_rain": 88,
            "chance_of_snow": 0,
            "cloud": 87,
            "condition": {
              "code": 1063,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "text": "Patchy rain nearby"
            },
            "dewpoint_c": 10.4,
            "dewpoint_f": 50.7,
            "feelslike_c": 15.7,
            "feelslike_f": 60.3,
            "gust_kph": 20.3,
            "gust_mph": 12.6,
            "heatindex_c": 15.7,
            "heatindex_f": 60.3,
            "humidity": 70,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.02,
            "pressure_in": 30.06,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 15.7,
            "temp_f": 60.3,
            "time": "2024-04-10 19:00",
            "time_epoch": 1712746800,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 119,
            "wind_dir": "ESE",
            "wind_kph": 12.2,
            "wind_mph": 7.6,
            "windchill_c": 15.7,
            "windchill_f": 60.3
          },
          {
            "chance_of_rain": 100,
            "chance_of_snow": 0,
            "cloud": 92,
            "condition": {
              "code": 1153,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "text": "Light drizzle"
            },
            "dewpoint_c": 10.7,
            "dewpoint_f": 51.3,
            "feelslike_c": 15.2,
            "feelslike_f": 59.4,
            "gust_kph": 17.1,
            "gust_mph": 10.6,
            "heatindex_c": 15.2,
            "heatindex_f": 59.4,
            "humidity": 75,
            "is_day": 0,
            "precip_in": 0.01,
            "precip_mm": 0.26,
            "pressure_in": 30.07,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 15.2,
            "temp_f": 59.4,
            "time": "2024-04-10 20:00",
            "time_epoch": 1712750400,
            "uv": 1.0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "wind_kph": 10.1,
            "wind_mph": 6.3,
            "windchill_c": 15.2,
            "windchill_f": 59.4
          },
          {
            "chance_of_rain": 100,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1153,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "text": "Light drizzle"
            },
            "dewpoint_c": 11.2,
            "dewpoint_f": 52.1,
            "feelslike_c": 14.7,
            "feelslike_f": 58.4,
            "gust_kph": 13.5,
            "gust_mph": 8.4,
            "heatindex_c": 14.8,
            "heatindex_f": 58.7,
            "humidity": 79,
            "is_day": 0,
            "precip_in": 0.01,
            "precip_mm": 0.31,
            "pressure_in": 30.09,
            "pressure_mb": 1019.0,
            "snow_cm": 0.0,
            "temp_c": 14.8,
            "temp_f": 58.7,
            "time": "2024-04-10 21:00",
            "time_epoch": 1712754000,
            "uv": 1.0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 84,
            "wind_dir": "E",
            "wind_kph": 7.9,
            "wind_mph": 4.9,
            "windchill_c": 14.7,
            "windchill_f": 58.4
          },
          {
            "chance_of_rain": 100,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1153,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "text": "Light drizzle"
            },
            "dewpoint_c": 11.7,
            "dewpoint_f": 53.0,
            "feelslike_c": 13.8,
            "feelslike_f": 56.9,
            "gust_kph": 14.5,
            "gust_mph": 9.0,
            "heatindex_c": 14.2,
            "heatindex_f": 57.6,
            "humidity": 85,
            "is_day": 0,
            "precip_in": 0.02,
            "precip_mm": 0.4,
            "pressure_in": 30.1,
            "pressure_mb": 1019.0,
            "snow_cm": 0.0,
            "temp_c": 14.2,
            "temp_f": 57.6,
            "time": "2024-04-10 22:00",
            "time_epoch": 1712757600,
            "uv": 1.0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 82,
            "wind_dir": "E",
            "wind_kph": 8.6,
            "wind_mph": 5.4,
            "windchill_c": 13.8,
            "windchill_f": 56.9
          },
          {
            "chance_of_rain": 100,
            "chance_of_snow": 0,
            "cloud": 0,
            "condition": {
              "code": 1000,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "text": "Clear"
            },
            "dewpoint_c": 11.9,
            "dewpoint_f": 53.3,
            "feelslike_c": 13.3,
            "feelslike_f": 56.0,
            "gust_kph": 14.5,
            "gust_mph": 9.0,
            "heatindex_c": 13.8,
            "heatindex_f": 56.9,
            "humidity": 88,
            "is_day": 0,
            "precip_in": 0.02,
            "precip_mm": 0.56,
            "pressure_in": 30.06,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 16.0,
            "temp_f": 60.8,
            "time": "2024-04-10 23:00",
            "time_epoch": 1712761200,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 80,
            "wind_dir": "E",
            "wind_kph": 11.2,
            "wind_mph": 6.9,
            "windchill_c": 13.3,
            "windchill_f": 56.0
          }
        ]
      },
      {
        "astro": {
          "is_moon_up": 1,
          "is_sun_up": 1,
          "moon_illumination": 7,
          "moon_phase": "Waxing Crescent",
          "moonrise": "07:05 AM",
          "moonset": "09:37 PM",
          "sunrise": "05:41 AM",
          "sunset": "06:31 PM"
        },
        "date": "2024-04-11",
        "date_epoch": 1712793600,
        "day": {
          "avghumidity": 80,
          "avgtemp_c": 16.5,
          "avgtemp_f": 61.8,
          "avgvis_km": 9.7,
          "avgvis_miles": 6.0,
          "condition": {
            "code": 1063,
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "text": "Patchy rain nearby"
          },
          "daily_chance_of_rain": 89,
          "daily_chance_of_snow": 0,
          "daily_will_it_rain": 1,
          "daily_will_it_snow": 0,
          "maxtemp_c": 21.1,
          "maxtemp_f": 69.9,
          "maxwind_kph": 11.9,
          "maxwind_mph": 7.4,
          "mintemp_c": 12.9,
          "mintemp_f": 55.2,
          "totalprecip_in": 0.01,
          "totalprecip_mm": 0.22,
          "totalsnow_cm": 0.0,
          "uv": 7.0
        },
        "hour": [
          {
            "chance_of_rain": 100,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1153,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "text": "Light drizzle"
            },
            "dewpoint_c": 11.9,
            "dewpoint_f": 53.4,
            "feelslike_c": 12.7,
            "feelslike_f": 54.9,
            "gust_kph": 15.8,
            "gust_mph": 9.8,
            "heatindex_c": 13.4,
            "heatindex_f": 56.1,
            "humidity": 91,
            "is_day": 0,
            "precip_in": 0.01,
            "precip_mm": 0.19,
            "pressure_in": 30.09,
            "pressure_mb": 1019.0,
            "snow_cm": 0.0,
            "temp_c": 13.4,
            "temp_f": 56.1,
            "time": "2024-04-11 00:00",
            "time_epoch": 1712764800,
            "uv": 1.0,
            "vis_km": 2.0,
            "vis_miles": 1.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 103,
            "wind_dir": "ESE",
            "wind_kph": 9.7,
            "wind_mph": 6.0,
            "windchill_c": 12.7,
            "windchill_f": 54.9
          },
          {
            "chance_of_rain": 89,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1063,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "text": "Patchy rain nearby"
            },
            "dewpoint_c": 11.7,
            "dewpoint_f": 53.0,
            "feelslike_c": 12.2,
            "feelslike_f": 53.9,
            "gust_kph": 19.2,
            "gust_mph": 11.9,
            "heatindex_c": 13.2,
            "heatindex_f": 55.7,
            "humidity": 91,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.01,
            "pressure_in": 30.06,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 13.2,
            "temp_f": 55.7,
            "time": "2024-04-11 01:00",
            "time_epoch": 1712768400,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 109,
            "wind_dir": "ESE",
            "wind_kph": 11.9,
            "wind_mph": 7.4,
            "windchill_c": 12.2,
            "windchill_f": 53.9
          },
          {
            "chance_of_rain": 83,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1063,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "text": "Patchy rain nearby"
            },
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.8,
            "feelslike_c": 12.1,
            "feelslike_f": 53.7,
            "gust_kph": 17.5,
            "gust_mph": 10.9,
            "heatindex_c": 13.0,
            "heatindex_f": 55.4,
            "humidity": 91,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.01,
            "pressure_in": 30.05,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 13.0,
            "temp_f": 55.4,
            "time": "2024-04-11 02:00",
            "time_epoch": 1712772000,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 1,
            "will_it_snow": 0,
            "wind_degree": 115,
            "wind_dir": "ESE",
            "wind_kph": 11.2,
            "wind_mph": 6.9,
            "windchill_c": 12.1,
            "windchill_f": 53.7
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 71,
            "condition": {
              "code": 1006,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "text": "Cloudy "
            },
            "dewpoint_c": 11.4,
            "dewpoint_f": 52.5,
            "feelslike_c": 12.4,
            "feelslike_f": 54.3,
            "gust_kph": 13.2,
            "gust_mph": 8.2,
            "heatindex_c": 12.9,
            "heatindex_f": 55.3,
            "humidity": 90,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.04,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 12.9,
            "temp_f": 55.3,
            "time": "2024-04-11 03:00",
            "time_epoch": 1712775600,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 103,
            "wind_dir": "ESE",
            "wind_kph": 8.3,
            "wind_mph": 5.1,
            "windchill_c": 12.4,
            "windchill_f": 54.3
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1009,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "text": "Overcast "
            },
            "dewpoint_c": 11.3,
            "dewpoint_f": 52.3,
            "feelslike_c": 12.7,
            "feelslike_f": 54.8,
            "gust_kph": 10.5,
            "gust_mph": 6.5,
            "heatindex_c": 12.9,
            "heatindex_f": 55.2,
            "humidity": 90,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.04,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 12.9,
            "temp_f": 55.2,
            "time": "2024-04-11 04:00",
            "time_epoch": 1712779200,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "wind_kph": 6.5,
            "wind_mph": 4.0,
            "windchill_c": 12.7,
            "windchill_f": 54.8
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1009,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "text": "Overcast "
            },
            "dewpoint_c": 11.4,
            "dewpoint_f": 52.6,
            "feelslike_c": 13.2,
            "feelslike_f": 55.8,
            "gust_kph": 8.6,
            "gust_mph": 5.3,
            "heatindex_c": 13.1,
            "heatindex_f": 55.6,
            "humidity": 89,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.05,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 13.1,
            "temp_f": 55.6,
            "time": "2024-04-11 05:00",
            "time_epoch": 1712782800,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "wind_kph": 5.4,
            "wind_mph": 3.4,
            "windchill_c": 13.2,
            "windchill_f": 55.8
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1009,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "text": "Overcast "
            },
            "dewpoint_c": 11.4,
            "dewpoint_f": 52.5,
            "feelslike_c": 13.3,
            "feelslike_f": 56.0,
            "gust_kph": 8.1,
            "gust_mph": 5.0,
            "heatindex_c": 13.1,
            "heatindex_f": 55.7,
            "humidity": 89,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.06,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 13.1,
            "temp_f": 55.7,
            "time": "2024-04-11 06:00",
            "time_epoch": 1712786400,
            "uv": 3.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 95,
            "wind_dir": "E",
            "wind_kph": 5.0,
            "wind_mph": 3.1,
            "windchill_c": 13.3,
            "windchill_f": 56.0
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1009,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "text": "Overcast "
            },
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.6,
            "feelslike_c": 13.0,
            "feelslike_f": 55.5,
            "gust_kph": 10.9,
            "gust_mph": 6.8,
            "heatindex_c": 13.3,
            "heatindex_f": 55.9,
            "humidity": 89,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.07,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 13.3,
            "temp_f": 55.9,
            "time": "2024-04-11 07:00",
            "time_epoch": 1712790000,
            "uv": 3.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 63,
            "wind_dir": "ENE",
            "wind_kph": 6.8,
            "wind_mph": 4.3,
            "windchill_c": 13.0,
            "windchill_f": 55.5
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 88,
            "condition": {
              "code": 1009,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "text": "Overcast "
            },
            "dewpoint_c": 11.5,
            "dewpoint_f": 52.7,
            "feelslike_c": 13.9,
            "feelslike_f": 56.9,
            "gust_kph": 9.6,
            "gust_mph": 6.0,
            "heatindex_c": 13.9,
            "heatindex_f": 57.0,
            "humidity": 86,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.08,
            "pressure_mb": 1019.0,
            "snow_cm": 0.0,
            "temp_c": 13.9,
            "temp_f": 57.0,
            "time": "2024-04-11 08:00",
            "time_epoch": 1712793600,
            "uv": 3.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 77,
            "wind_dir": "ENE",
            "wind_kph": 6.5,
            "wind_mph": 4.0,
            "windchill_c": 13.9,
            "windchill_f": 56.9
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 32,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 11.7,
            "dewpoint_f": 53.1,
            "feelslike_c": 15.1,
            "feelslike_f": 59.1,
            "gust_kph": 9.1,
            "gust_mph": 5.7,
            "heatindex_c": 15.0,
            "heatindex_f": 59.0,
            "humidity": 81,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.08,
            "pressure_mb": 1019.0,
            "snow_cm": 0.0,
            "temp_c": 15.0,
            "temp_f": 59.0,
            "time": "2024-04-11 09:00",
            "time_epoch": 1712797200,
            "uv": 4.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 113,
            "wind_dir": "ESE",
            "wind_kph": 6.8,
            "wind_mph": 4.3,
            "windchill_c": 15.1,
            "windchill_f": 59.1
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 31,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 12.1,
            "dewpoint_f": 53.7,
            "feelslike_c": 16.1,
            "feelslike_f": 61.0,
            "gust_kph": 8.1,
            "gust_mph": 5.0,
            "heatindex_c": 16.1,
            "heatindex_f": 61.0,
            "humidity": 77,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.08,
            "pressure_mb": 1019.0,
            "snow_cm": 0.0,
            "temp_c": 16.1,
            "temp_f": 61.0,
            "time": "2024-04-11 10:00",
            "time_epoch": 1712800800,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 107,
            "wind_dir": "ESE",
            "wind_kph": 6.5,
            "wind_mph": 4.0,
            "windchill_c": 16.1,
            "windchill_f": 61.0
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 33,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 12.8,
            "dewpoint_f": 55.0,
            "feelslike_c": 18.7,
            "feelslike_f": 65.6,
            "gust_kph": 7.5,
            "gust_mph": 4.6,
            "heatindex_c": 18.7,
            "heatindex_f": 65.6,
            "humidity": 68,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.07,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 18.7,
            "temp_f": 65.6,
            "time": "2024-04-11 11:00",
            "time_epoch": 1712804400,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 120,
            "wind_dir": "ESE",
            "wind_kph": 6.5,
            "wind_mph": 4.0,
            "windchill_c": 18.7,
            "windchill_f": 65.6
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 35,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 13.0,
            "dewpoint_f": 55.3,
            "feelslike_c": 19.4,
            "feelslike_f": 66.8,
            "gust_kph": 7.1,
            "gust_mph": 4.4,
            "heatindex_c": 19.4,
            "heatindex_f": 66.8,
            "humidity": 66,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.05,
            "pressure_mb": 1018.0,
            "snow_cm": 0.0,
            "temp_c": 19.4,
            "temp_f": 66.8,
            "time": "2024-04-11 12:00",
            "time_epoch": 1712808000,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 132,
            "wind_dir": "SE",
            "wind_kph": 6.1,
            "wind_mph": 3.8,
            "windchill_c": 19.4,
            "windchill_f": 66.8
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 40,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 13.3,
            "dewpoint_f": 56.0,
            "feelslike_c": 20.4,
            "feelslike_f": 68.7,
            "gust_kph": 6.6,
            "gust_mph": 4.1,
            "heatindex_c": 20.4,
            "heatindex_f": 68.7,
            "humidity": 64,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.03,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 20.4,
            "temp_f": 68.7,
            "time": "2024-04-11 13:00",
            "time_epoch": 1712811600,
            "uv": 6.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 130,
            "wind_dir": "SE",
            "wind_kph": 5.8,
            "wind_mph": 3.6,
            "windchill_c": 20.4,
            "windchill_f": 68.7
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 49,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 13.7,
            "dewpoint_f": 56.6,
            "feelslike_c": 20.9,
            "feelslike_f": 69.6,
            "gust_kph": 7.9,
            "gust_mph": 4.9,
            "heatindex_c": 20.9,
            "heatindex_f": 69.6,
            "humidity": 63,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.01,
            "pressure_mb": 1016.0,
            "snow_cm": 0.0,
            "temp_c": 20.9,
            "temp_f": 69.6,
            "time": "2024-04-11 14:00",
            "time_epoch": 1712815200,
            "uv": 6.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 149,
            "wind_dir": "SSE",
            "wind_kph": 6.8,
            "wind_mph": 4.3,
            "windchill_c": 20.9,
            "windchill_f": 69.6
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 36,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 13.8,
            "dewpoint_f": 56.9,
            "feelslike_c": 21.0,
            "feelslike_f": 69.8,
            "gust_kph": 7.7,
            "gust_mph": 4.8,
            "heatindex_c": 24.4,
            "heatindex_f": 76.0,
            "humidity": 63,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 29.98,
            "pressure_mb": 1015.0,
            "snow_cm": 0.0,
            "temp_c": 21.0,
            "temp_f": 69.8,
            "time": "2024-04-11 15:00",
            "time_epoch": 1712818800,
            "uv": 6.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 127,
            "wind_dir": "SE",
            "wind_kph": 6.5,
            "wind_mph": 4.0,
            "windchill_c": 21.0,
            "windchill_f": 69.8
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 45,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 14.2,
            "dewpoint_f": 57.5,
            "feelslike_c": 21.1,
            "feelslike_f": 69.9,
            "gust_kph": 8.6,
            "gust_mph": 5.3,
            "heatindex_c": 24.4,
            "heatindex_f": 76.0,
            "humidity": 65,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 29.98,
            "pressure_mb": 1015.0,
            "snow_cm": 0.0,
            "temp_c": 21.1,
            "temp_f": 69.9,
            "time": "2024-04-11 16:00",
            "time_epoch": 1712822400,
            "uv": 6.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 102,
            "wind_dir": "ESE",
            "wind_kph": 6.8,
            "wind_mph": 4.3,
            "windchill_c": 21.1,
            "windchill_f": 69.9
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 62,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 14.7,
            "dewpoint_f": 58.4,
            "feelslike_c": 20.6,
            "feelslike_f": 69.1,
            "gust_kph": 9.3,
            "gust_mph": 5.8,
            "heatindex_c": 20.6,
            "heatindex_f": 69.1,
            "humidity": 69,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 29.99,
            "pressure_mb": 1016.0,
            "snow_cm": 0.0,
            "temp_c": 20.6,
            "temp_f": 69.1,
            "time": "2024-04-11 17:00",
            "time_epoch": 1712826000,
            "uv": 6.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 112,
            "wind_dir": "ESE",
            "wind_kph": 6.8,
            "wind_mph": 4.3,
            "windchill_c": 20.6,
            "windchill_f": 69.1
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 53,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 14.8,
            "dewpoint_f": 58.6,
            "feelslike_c": 19.1,
            "feelslike_f": 66.3,
            "gust_kph": 12.5,
            "gust_mph": 7.8,
            "heatindex_c": 19.1,
            "heatindex_f": 66.3,
            "humidity": 76,
            "is_day": 1,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 29.99,
            "pressure_mb": 1016.0,
            "snow_cm": 0.0,
            "temp_c": 19.1,
            "temp_f": 66.3,
            "time": "2024-04-11 18:00",
            "time_epoch": 1712829600,
            "uv": 5.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 123,
            "wind_dir": "ESE",
            "wind_kph": 7.6,
            "wind_mph": 4.7,
            "windchill_c": 19.1,
            "windchill_f": 66.3
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 77,
            "condition": {
              "code": 1006,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "text": "Cloudy "
            },
            "dewpoint_c": 14.4,
            "dewpoint_f": 57.9,
            "feelslike_c": 18.2,
            "feelslike_f": 64.7,
            "gust_kph": 12.9,
            "gust_mph": 8.0,
            "heatindex_c": 18.2,
            "heatindex_f": 64.7,
            "humidity": 79,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 29.99,
            "pressure_mb": 1016.0,
            "snow_cm": 0.0,
            "temp_c": 18.2,
            "temp_f": 64.7,
            "time": "2024-04-11 19:00",
            "time_epoch": 1712833200,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 102,
            "wind_dir": "ESE",
            "wind_kph": 7.2,
            "wind_mph": 4.5,
            "windchill_c": 18.2,
            "windchill_f": 64.7
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 70,
            "condition": {
              "code": 1006,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "text": "Cloudy "
            },
            "dewpoint_c": 14.4,
            "dewpoint_f": 57.8,
            "feelslike_c": 17.5,
            "feelslike_f": 63.5,
            "gust_kph": 15.9,
            "gust_mph": 9.9,
            "heatindex_c": 17.5,
            "heatindex_f": 63.5,
            "humidity": 82,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.0,
            "pressure_mb": 1016.0,
            "snow_cm": 0.0,
            "temp_c": 17.5,
            "temp_f": 63.5,
            "time": "2024-04-11 20:00",
            "time_epoch": 1712836800,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 106,
            "wind_dir": "ESE",
            "wind_kph": 8.6,
            "wind_mph": 5.4,
            "windchill_c": 17.5,
            "windchill_f": 63.5
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 100,
            "condition": {
              "code": 1009,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "text": "Overcast "
            },
            "dewpoint_c": 14.3,
            "dewpoint_f": 57.8,
            "feelslike_c": 17.0,
            "feelslike_f": 62.6,
            "gust_kph": 11.5,
            "gust_mph": 7.1,
            "heatindex_c": 17.0,
            "heatindex_f": 62.6,
            "humidity": 84,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.03,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 17.0,
            "temp_f": 62.6,
            "time": "2024-04-11 21:00",
            "time_epoch": 1712840400,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 110,
            "wind_dir": "ESE",
            "wind_kph": 6.1,
            "wind_mph": 3.8,
            "windchill_c": 17.0,
            "windchill_f": 62.6
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 53,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 14.1,
            "dewpoint_f": 57.3,
            "feelslike_c": 16.7,
            "feelslike_f": 62.0,
            "gust_kph": 17.0,
            "gust_mph": 10.6,
            "heatindex_c": 16.7,
            "heatindex_f": 62.0,
            "humidity": 85,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.02,
            "pressure_mb": 1016.0,
            "snow_cm": 0.0,
            "temp_c": 16.7,
            "temp_f": 62.0,
            "time": "2024-04-11 22:00",
            "time_epoch": 1712844000,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 101,
            "wind_dir": "ESE",
            "wind_kph": 9.0,
            "wind_mph": 5.6,
            "windchill_c": 16.7,
            "windchill_f": 62.0
          },
          {
            "chance_of_rain": 0,
            "chance_of_snow": 0,
            "cloud": 55,
            "condition": {
              "code": 1003,
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "text": "Partly Cloudy "
            },
            "dewpoint_c": 13.8,
            "dewpoint_f": 56.8,
            "feelslike_c": 16.4,
            "feelslike_f": 61.5,
            "gust_kph": 11.7,
            "gust_mph": 7.3,
            "heatindex_c": 16.4,
            "heatindex_f": 61.5,
            "humidity": 85,
            "is_day": 0,
            "precip_in": 0.0,
            "precip_mm": 0.0,
            "pressure_in": 30.02,
            "pressure_mb": 1017.0,
            "snow_cm": 0.0,
            "temp_c": 16.4,
            "temp_f": 61.5,
            "time": "2024-04-11 23:00",
            "time_epoch": 1712847600,
            "uv": 1.0,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "will_it_rain": 0,
            "will_it_snow": 0,
            "wind_degree": 105,
            "wind_dir": "ESE",
            "wind_kph": 6.5,
            "wind_mph": 4.0,
            "windchill_c": 16.4,
            "windchill_f": 61.5
          }
        ]
      }
    ]
  },
  "location": {
    "country": "China",
    "lat": 32.06,
    "localtime": "2024-04-10 23:22",
    "localtime_epoch": 1712762553,
    "lon": 118.78,
    "name": "Nanjing",
    "region": "Jiangsu",
    "tz_id": "Asia/Shanghai"
  }
}

export {
  mock_data
}